import Head from 'next/head'

import Landing from "../components/landing";
import React, {useState} from "react";
import Popup from "../components/popup";
import Invite from "../components/invite";
import Alertify from "../components/alertify";

export default function Home() {

    const [statusPopup , setStatusPopup] = useState(false)
    const [statusInvite , setStatusInvite] = useState(false)


    return (<div className="position-relative">
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
        </Head>
        <main className='container-fluid font-pinar p-0 m-0 vh-100 main'>
            <Landing setStatusInvite={setStatusInvite} setStatusPopup={setStatusPopup}/>
        </main>
        {
            statusPopup ?   <Popup setStatusInvite={setStatusInvite} setStatusPopup={setStatusPopup} />  : ''
        }
        {
            statusInvite ?   <Invite setStatusInvite={setStatusInvite} />  : ''
        }
        <Alertify />

    </div>)
}
